/*
 * Frame.java
 *
 * Created on 10 août 2003, 19:23
 */

import java.util.*;


/**
 *
 * @author  Rodrigo
 */
public class JSmoothPropertiesDisplayer extends java.awt.Frame
{
	
	/** Creates new form Frame */
	public JSmoothPropertiesDisplayer()
	{
		initComponents();
		displayInformation();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents()//GEN-BEGIN:initComponents
	{
		java.awt.GridBagConstraints gridBagConstraints;
		
		label1 = new java.awt.Label();
		m_text = new java.awt.TextArea();
		m_buttonClose = new java.awt.Button();
		
		setLayout(new java.awt.GridBagLayout());
		
		addWindowListener(new java.awt.event.WindowAdapter()
		{
			public void windowClosing(java.awt.event.WindowEvent evt)
			{
				exitForm(evt);
			}
		});
		
		label1.setAlignment(java.awt.Label.CENTER);
		label1.setFont(new java.awt.Font("Dialog", 0, 18));
		label1.setText("JSmooth Sample Program");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
		add(label1, gridBagConstraints);
		
		m_text.setEditable(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		gridBagConstraints.weightx = 1.0;
		gridBagConstraints.weighty = 1.0;
		add(m_text, gridBagConstraints);
		
		m_buttonClose.setLabel("Close");
		m_buttonClose.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				buttonCloseActionPerformed(evt);
			}
		});
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		add(m_buttonClose, gridBagConstraints);
		
		pack();
	}//GEN-END:initComponents

	private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonCloseActionPerformed
	{//GEN-HEADEREND:event_buttonCloseActionPerformed
		// Add your handling code here:
		System.exit(0);
	}//GEN-LAST:event_buttonCloseActionPerformed
	
	/** Exit the Application */
	private void exitForm(java.awt.event.WindowEvent evt)//GEN-FIRST:event_exitForm
	{
		System.exit(0);
	}//GEN-LAST:event_exitForm
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		new JSmoothPropertiesDisplayer().show();
	}

	private void displayInformation()
	{
		StringBuffer out = new StringBuffer();
		out.append("-- Sample --\n\n");
		
		out.append("System Properties:\n\n");
		Properties props = System.getProperties();
		for (Enumeration e = props.propertyNames(); e.hasMoreElements(); )
		{
			String key = (String)e.nextElement();
			out.append(key);
			out.append(" = ");
			out.append(props.getProperty(key));
			out.append("\n");
		}
		System.out.println(out.toString());
		m_text.setText(out.toString());
	}
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private java.awt.Label label1;
	private java.awt.Button m_buttonClose;
	private java.awt.TextArea m_text;
	// End of variables declaration//GEN-END:variables
	
}
