/*
  JSmooth: a VM wrapper toolkit for Windows
  Copyright (C) 2003 Rodrigo Reyes <reyes@charabia.net>

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

*/

package net.charabia.jsmoothgen.application.gui.util;

import javax.swing.*;

public class FileSelectionTextField extends javax.swing.JPanel
{
	
	/** Creates new form BeanForm */
	public FileSelectionTextField()
	{
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents()//GEN-BEGIN:initComponents
	{
		m_fileChooser = new javax.swing.JFileChooser();
		m_filename = new javax.swing.JTextField();
		m_buttonFileSelection = new javax.swing.JButton();
		
		
		setLayout(new java.awt.BorderLayout());
		
		add(m_filename, java.awt.BorderLayout.CENTER);
		
		m_buttonFileSelection.setText("...");
		m_buttonFileSelection.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				buttonFileSelectionActionPerformed(evt);
			}
		});
		
		add(m_buttonFileSelection, java.awt.BorderLayout.EAST);
		
	}//GEN-END:initComponents

	private void buttonFileSelectionActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonFileSelectionActionPerformed
	{//GEN-HEADEREND:event_buttonFileSelectionActionPerformed
		// Add your handling code here:
		java.io.File cur = new java.io.File(m_filename.getText());
		m_fileChooser.setSelectedFile(cur);
		if (m_fileChooser.showDialog(this, "Select") == JFileChooser.APPROVE_OPTION)
		{
			java.io.File f = m_fileChooser.getSelectedFile();
			m_filename.setText(f.getAbsolutePath());
		}
	}//GEN-LAST:event_buttonFileSelectionActionPerformed
	
	public void setFile(java.io.File f)
	{
		m_filename.setText(f.getAbsolutePath());
	}
	
	public java.io.File getFile()
	{
		return new java.io.File(m_filename.getText());
	}
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton m_buttonFileSelection;
	private javax.swing.JFileChooser m_fileChooser;
	private javax.swing.JTextField m_filename;
	// End of variables declaration//GEN-END:variables
	
}
