/*
  JSmooth: a VM wrapper toolkit for Windows
  Copyright (C) 2003 Rodrigo Reyes <reyes@charabia.net>
 
  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.
 
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
 
  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 
 */


package net.charabia.jsmoothgen.application.gui.util;

import java.util.jar.*;
import java.util.*;
import javax.swing.tree.*;

public class JarClassChooser extends javax.swing.JDialog {

    public class JarEntryTreeNode extends javax.swing.tree.DefaultMutableTreeNode {
        public JarEntryTreeNode(String value) {
            super(value);
        }
        
        public void add(String[] items) {
            JarEntryTreeNode current = this;
            for (int i=0; i<items.length; i++) {
                JarEntryTreeNode next = null;
                
                for (Enumeration e=current.children(); (e.hasMoreElements()) && (next == null); ) {
                    JarEntryTreeNode jtn = (JarEntryTreeNode)e.nextElement();
                    if (jtn.getUserObject().equals(items[i])) {
                        next = jtn;
                    }
                }
                
                if (next == null) {
                    next = new JarEntryTreeNode(items[i]);
                    current.add(next);
                    current = next;
                }
                else {
                    current = next;
                }
            }
        }
    }
    
    
    /** Creates new form JarClassChooser */
    public JarClassChooser(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public void setJar(JarFile jf) {

        JarEntryTreeNode root = new JarEntryTreeNode(jf.getName());
        
        for (Enumeration e=jf.entries(); e.hasMoreElements(); ) {

            JarEntry entry = (JarEntry)e.nextElement();
            String[] res = entry.toString().split("/");
            System.out.println("JarEntry: " + entry);
            root.add(res);
        }
        m_tree.setModel(new DefaultTreeModel(root));        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        m_tree = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
        jLabel1.setText("Select a class...");
        jPanel1.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 10, 10)));
        jScrollPane1.setViewportView(m_tree);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/stock_calc-accept-16.png")));
        jButton1.setText("Select");
        jPanel2.add(jButton1);

        jPanel2.add(jSeparator1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/stock_calc-cancel-16.png")));
        jButton2.setText("Cancel");
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }//GEN-END:initComponents
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        new JarClassChooser(new javax.swing.JFrame(), true).show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTree m_tree;
    // End of variables declaration//GEN-END:variables
    
}
