/*
 * AboutBox.java
 *
 * Created on 10 août 2003, 00:52
 */

package net.charabia.jsmoothgen.application.gui;

/**
 *
 * @author  Rodrigo
 */
public class AboutBox extends javax.swing.JDialog
{
	
	/** Creates new form AboutBox */
	public AboutBox(java.awt.Frame parent, boolean modal)
	{
		super(parent, modal);
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents()//GEN-BEGIN:initComponents
	{
		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		m_buttonOk = new javax.swing.JButton();
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("About JSmooth");
		setModal(true);
		setResizable(false);
		addWindowListener(new java.awt.event.WindowAdapter()
		{
			public void windowClosing(java.awt.event.WindowEvent evt)
			{
				closeDialog(evt);
			}
		});
		
		jPanel1.setLayout(new java.awt.BorderLayout());
		
		jPanel1.setBorder(new javax.swing.border.CompoundBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(5, 5, 5, 5)), new javax.swing.border.EtchedBorder()));
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/gnome-application-x-jar.png")));
		jLabel1.setText("<html><p align=\"center\"<big><strong>JSmooth</strong></big><p>JSmooth is a Java Executable Wrapper that makes a standard Windows executable binary (.exe) from a jar file. It makes java deployment much smoother and user-friendly, as it is able to find a Java VM by itself.</html>");
		jLabel1.setFocusable(false);
		jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);
		
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
		jLabel2.setText("<html>Information<ul><li>Web site: https://sourceforge.net/projects/jsmooth/</li><li>Author: Rodrigo Reyes &lt;reyes@users.sourceforge.net&gt; </ul></html>");
		jPanel1.add(jLabel2, java.awt.BorderLayout.SOUTH);
		
		getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
		
		m_buttonOk.setText("OK");
		m_buttonOk.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				buttonOkActionPerformed(evt);
			}
		});
		
		jPanel2.add(m_buttonOk);
		
		getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);
		
		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
		setBounds((screenSize.width-400)/2, (screenSize.height-300)/2, 400, 300);
	}//GEN-END:initComponents

	private void buttonOkActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonOkActionPerformed
	{//GEN-HEADEREND:event_buttonOkActionPerformed
		// Add your handling code here:
		dispose();
	}//GEN-LAST:event_buttonOkActionPerformed
	
	/** Closes the dialog */
	private void closeDialog(java.awt.event.WindowEvent evt)//GEN-FIRST:event_closeDialog
	{
		setVisible(false);
		dispose();
	}//GEN-LAST:event_closeDialog
	
	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		new AboutBox(new javax.swing.JFrame(), true).show();
	}
	
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JButton m_buttonOk;
	// End of variables declaration//GEN-END:variables
	
}
