/*
 * Executable.java
 *
 * Created on 7 août 2003, 15:03
 */

package net.charabia.jsmoothgen.application.gui;

/**
 *
 * @author  Rodrigo
 */
public class Executable extends javax.swing.JPanel
{
	
	/** Creates new form BeanForm */
	public Executable()
	{
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents()//GEN-BEGIN:initComponents
	{
		java.awt.GridBagConstraints gridBagConstraints;
		
		jLabel1 = new javax.swing.JLabel();
		m_executableNameField = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		
		setLayout(new java.awt.GridBagLayout());
		
		jLabel1.setText("Executable Name");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.ipadx = 5;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
		gridBagConstraints.weightx = 0.1;
		add(jLabel1, gridBagConstraints);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.ipadx = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
		gridBagConstraints.weightx = 0.8;
		add(m_executableNameField, gridBagConstraints);
		
		jLabel2.setText("Executable Icon");
		add(jLabel2, new java.awt.GridBagConstraints());
		
		jPanel2.setBorder(new javax.swing.border.EtchedBorder());
		jPanel2.setEnabled(false);
		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/classes/gnome-application-x-gzip.png")));
		jLabel3.setEnabled(false);
		jPanel2.add(jLabel3);
		
		jButton1.setText("...");
		jButton1.setEnabled(false);
		jPanel2.add(jButton1);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
		add(jPanel2, gridBagConstraints);
		
	}//GEN-END:initComponents
	
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTextField m_executableNameField;
	// End of variables declaration//GEN-END:variables
		
	public String getExecutableName()
	{
		return m_executableNameField.getText();
	}
}
