/*
  JSmooth: a VM wrapper toolkit for Windows
  Copyright (C) 2003 Rodrigo Reyes <reyes@charabia.net>

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program; if not, write to the Free Software
  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

*/


/*
 * SkeletonEditor.java
 *
 * Created on 7 août 2003, 22:23
 */

package net.charabia.jsmoothgen.skeleton;

import javax.swing.*;
import java.io.*;


public class SkeletonEditor extends javax.swing.JFrame
{
	
	/** Creates new form SkeletonEditor */
	public SkeletonEditor()
	{
		initComponents();
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents()//GEN-BEGIN:initComponents
	{
		java.awt.GridBagConstraints gridBagConstraints;
		
		m_fileChooser = new javax.swing.JFileChooser();
		jPanel1 = new javax.swing.JPanel();
		jLabel5 = new javax.swing.JLabel();
		m_exeName = new javax.swing.JTextField();
		m_labelName = new javax.swing.JLabel();
		m_name = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		m_description = new javax.swing.JEditorPane();
		jLabel2 = new javax.swing.JLabel();
		m_categoryName = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		m_jarId = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		m_propsId = new javax.swing.JTextField();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		m_menuNew = new javax.swing.JMenuItem();
		m_menuLoad = new javax.swing.JMenuItem();
		jSeparator1 = new javax.swing.JSeparator();
		m_menuSave = new javax.swing.JMenuItem();
		jSeparator2 = new javax.swing.JSeparator();
		m_menuExit = new javax.swing.JMenuItem();
		
		m_fileChooser.setCurrentDirectory(new java.io.File("c:\\"));
		m_fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter()
		{
			public boolean accept(File f)
			{
				if (f.toString().endsWith(".skel"))
					return true;
				if (f.isDirectory())
					return true;
				return false;
			}
			public String getDescription()
			{
				return "JSmooth Skeletons (*.skel)";
			}
		});
		m_fileChooser.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
		
		getContentPane().setLayout(new java.awt.GridBagLayout());
		
		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("JSmooth Skeleton Editor");
		addWindowListener(new java.awt.event.WindowAdapter()
		{
			public void windowClosing(java.awt.event.WindowEvent evt)
			{
				exitForm(evt);
			}
		});
		
		jPanel1.setLayout(new java.awt.GridBagLayout());
		
		jPanel1.setBorder(new javax.swing.border.EtchedBorder());
		jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel5.setText("Executable Name");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
		jPanel1.add(jLabel5, gridBagConstraints);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 0.5;
		jPanel1.add(m_exeName, gridBagConstraints);
		
		m_labelName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		m_labelName.setText("Short Name");
		m_labelName.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
		jPanel1.add(m_labelName, gridBagConstraints);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 0.5;
		jPanel1.add(m_name, gridBagConstraints);
		
		jLabel1.setText("Description");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
		jPanel1.add(jLabel1, gridBagConstraints);
		
		jScrollPane1.setViewportView(m_description);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 0.5;
		gridBagConstraints.weighty = 0.5;
		jPanel1.add(jScrollPane1, gridBagConstraints);
		
		jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel2.setText("Category Name");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
		jPanel1.add(jLabel2, gridBagConstraints);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 0.5;
		jPanel1.add(m_categoryName, gridBagConstraints);
		
		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel3.setText("Resource Id for JAR");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
		jPanel1.add(jLabel3, gridBagConstraints);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		jPanel1.add(m_jarId, gridBagConstraints);
		
		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
		jLabel4.setText("Resource Id for Properties");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
		jPanel1.add(jLabel4, gridBagConstraints);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		jPanel1.add(m_propsId, gridBagConstraints);
		
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.gridheight = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints.weightx = 0.9;
		gridBagConstraints.weighty = 0.9;
		getContentPane().add(jPanel1, gridBagConstraints);
		
		jMenu1.setText("System");
		m_menuNew.setText("New");
		m_menuNew.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				menuNewActionPerformed(evt);
			}
		});
		
		jMenu1.add(m_menuNew);
		
		m_menuLoad.setText("Load");
		m_menuLoad.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				menuLoadActionPerformed(evt);
			}
		});
		
		jMenu1.add(m_menuLoad);
		
		jMenu1.add(jSeparator1);
		
		m_menuSave.setText("Save");
		m_menuSave.addActionListener(new java.awt.event.ActionListener()
		{
			public void actionPerformed(java.awt.event.ActionEvent evt)
			{
				menuSaveActionPerformed(evt);
			}
		});
		
		jMenu1.add(m_menuSave);
		
		jMenu1.add(jSeparator2);
		
		m_menuExit.setText("Exit");
		jMenu1.add(m_menuExit);
		
		jMenuBar1.add(jMenu1);
		
		setJMenuBar(jMenuBar1);
		
		java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
		setBounds((screenSize.width-400)/2, (screenSize.height-300)/2, 400, 300);
	}//GEN-END:initComponents

	private void menuSaveActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuSaveActionPerformed
	{//GEN-HEADEREND:event_menuSaveActionPerformed
		// Add your handling code here:
		if ( m_fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION)
		{
			File f = m_fileChooser.getSelectedFile();
			if (f.toString().endsWith(".skel") == false)
			{
				f = new File(f.getAbsolutePath() + ".skel");
			}	
			System.out.println("loading " + m_fileChooser.getSelectedFile().toString());
			try {
				SkeletonBean skel = getSkeleton();
				SkeletonPersistency.save(f, skel);
			} catch (IOException iox)
			{
				iox.printStackTrace();
			}
		}
	}//GEN-LAST:event_menuSaveActionPerformed

	private void menuLoadActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuLoadActionPerformed
	{//GEN-HEADEREND:event_menuLoadActionPerformed
		// Add your handling code here:
		if ( m_fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION)
		{
			File f = m_fileChooser.getSelectedFile();
			System.out.println("loading " + m_fileChooser.getSelectedFile().toString());
			try {
				SkeletonBean skel = SkeletonPersistency.load(f);
				setSkeleton(skel);
			} catch (IOException iox)
			{
				iox.printStackTrace();
			}
		}
	}//GEN-LAST:event_menuLoadActionPerformed

	private void menuNewActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_menuNewActionPerformed
	{//GEN-HEADEREND:event_menuNewActionPerformed
		// Add your handling code here:
		SkeletonBean skel = new SkeletonBean();
		setSkeleton(skel);
	}//GEN-LAST:event_menuNewActionPerformed
	
	/** Exit the Application */
	private void exitForm(java.awt.event.WindowEvent evt)//GEN-FIRST:event_exitForm
	{
		System.exit(0);
	}//GEN-LAST:event_exitForm
	
	public void setSkeleton(SkeletonBean skel)
	{
		m_name.setText(skel.getShortName());
		m_description.setText(skel.getDescription());
		m_categoryName.setText(skel.getResourceCategory());
		m_jarId.setText(new Integer(skel.getResourceJarId()).toString());
		m_propsId.setText(new Integer(skel.getResourcePropsId()).toString());
		m_exeName.setText(skel.getExecutableName());
	}
	
	public SkeletonBean getSkeleton()
	{
		SkeletonBean skel = new SkeletonBean();
		skel.setExecutableName(m_exeName.getText());
		skel.setShortName(m_name.getText());
		skel.setDescription(m_description.getText());
		skel.setResourceCategory(m_categoryName.getText());
		skel.setResourceJarId(Integer.parseInt(m_jarId.getText()));
		skel.setResourcePropsId(Integer.parseInt(m_propsId.getText()));
		
		return skel;
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[])
	{
		new SkeletonEditor().show();
	}
	
	
	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JTextField m_categoryName;
	private javax.swing.JEditorPane m_description;
	private javax.swing.JTextField m_exeName;
	private javax.swing.JFileChooser m_fileChooser;
	private javax.swing.JTextField m_jarId;
	private javax.swing.JLabel m_labelName;
	private javax.swing.JMenuItem m_menuExit;
	private javax.swing.JMenuItem m_menuLoad;
	private javax.swing.JMenuItem m_menuNew;
	private javax.swing.JMenuItem m_menuSave;
	private javax.swing.JTextField m_name;
	private javax.swing.JTextField m_propsId;
	// End of variables declaration//GEN-END:variables
	
}
